manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: inorichi
      url-base: https://github.com/inorichi
  projects:
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: feat/pointers-move-scroll
    #   import: app/west.yml
    - name: zmk
      url: https://github.com/sky-bro/zmk
      revision: k4i-sweep-kbd
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: main
  self:
    path: config
